// name, file in pngs/ (null = no image yet)
var CHARACTERS = [
  ["peter griffin", "peter-griffin.webp"],
  ["lois griffin", "lois-griffin.webp"],
  ["meg griffin", "meg-griffin.webp"],
  ["chris griffin", "chris-griffin.webp"],
  ["stewie griffin", "stewie-griffin.webp"],
  ["brian griffin", "brian-griffin.webp"],
  ["glenn quagmire", "glenn-quagmire.webp"],
  ["cleveland brown", "cleveland-brown.webp"],
  ["joe swanson", "joe-swanson.webp"],
  ["bonnie swanson", "bonnie-swanson.webp"],
  ["kevin swanson", "kevin-swanson.webp"],
  ["susie swanson", "susie-swanson.webp"],
  ["donna tubbs", "donna-tubbs.webp"],
  ["cleveland jr", "cleveland-brown-jr.webp"],
  ["rallo tubbs", "rallo-tubbs.webp"],
  ["roberta tubbs", "roberta-tubbs.webp"],
  ["mort goldman", "mort-goldman.webp"],
  ["muriel goldman", "muriel-goldman.webp"],
  ["neil goldman", "neil-goldman.webp"],
  ["carter pewterschmidt", "carter-pewterschmidt.webp"],
  ["barbara pewterschmidt", "barbara-pewterschmidt.webp"],
  ["carol west", "carol-west.webp"],
  ["patrick pewterschmidt", "patrick-pewterschmidt.webp"],
  ["francis griffin", "francis-griffin.webp"],
  ["thelma griffin", "thelma-griffin.webp"],
  ["mickey mcfinnigan", "mickey-mcfinnigan.webp"],
  ["bertram", "bertram.webp"],
  ["nate griffin", "nate-griffin.webp"],
  ["ida quagmire", "ida-quagmire.webp"],
  ["brenda quagmire", "brenda-quagmire.webp"],
  ["jillian", "jillian.webp"],
  ["herbert", "herbert.webp"],
  ["adam west", "adam-west.webp"],
  ["mayor west", "mayor-west.webp"],
  ["mayor wild west", "wild-west.webp"],
  ["tom tucker", "tom-tucker.webp"],
  ["jake tucker", "jake-tucker.webp"],
  ["diane simmons", "diane-simmons.webp"],
  ["joyce kinney", "joyce-kinney.webp"],
  ["ollie williams", "ollie-williams.webp"],
  ["dr hartman", "dr-hartman.webp"],
  ["principal shepherd", "principal-shepherd.webp"],
  ["connie d'amico", "connie-d-amico.webp"],
  ["esther", "esther.webp"],
  ["ruth cochamer", "ruth-cochamer.webp"],
  ["dylan flannigan", "dylan-flannigan.webp"],
  ["stella", "stella.webp"],
  ["angela", "angela.webp"],
  ["opie", "opie.webp"],
  ["jonathan weed", "jonathan-weed.webp"],
  ["seamus", "seamus.webp"],
  ["horace", "horace.webp"],
  ["gus", "gus.webp"],
  ["carl", "carl.webp"],
  ["consuela", "consuela.webp"],
  ["bruce", "bruce.webp"],
  ["jerome", "jerome.webp"],
  ["vinny", "vinny.webp"],
  ["jasper", "jasper.webp"],
  ["ricardo", "ricardo.webp"],
  ["rupert", "rupert.webp"],
  ["olivia fuller", "olivia-fuller.webp"],
  ["eliza pinchley", "eliza-pinchley.webp"],
  ["james woods", "james-woods.webp"],
  ["buzz killington", "buzz-killington.webp"],
  ["greased up deaf guy", "greased-up-deaf-guy.webp"],
  ["ernie the giant chicken", "ernie-the-giant-chicken.webp"],
  ["evil monkey", "evil-monkey.webp"],
  ["kool-aid man", "kool-aid-man.webp"],
  ["death", "death.webp"],
  ["god", "god.webp"],
  ["jesus", "jesus.webp"],
  ["santa", "santa-claus.webp"]
];

// name, file in places/
var PLACES = [
  ["spooner street", "spooner-street.webp"],
  ["drunken clam", "drunken-clam.webp"],
  ["quahog", "quahog.webp"],
  ["city hall", "quahog-city-hall.webp"],
  ["quahog 5 news", "quahog-5-news.webp"],
  ["pawtucket brewery", "pawtucket-brewery.webp"],
  ["goldman's pharmacy", "goldmans-pharmacy.webp"],
  ["quahog airport", "quahog-airport.webp"],
  ["quahog mall", "quahog-mall.webp"],
  ["toy factory", "happy-go-lucky-toy-factory.webp"],
  ["adam west high", "adam-west-high.webp"]
];
